# Generated by Django 4.2 on 2023-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(default='algo', max_length=1),
        ),
    ]
