# Generated by Django 4.2 on 2023-05-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_event_colorselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(max_length=1),
        ),
    ]
