# Generated by Django 4.2.1 on 2023-05-20 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_pet_remove_registerpet_online_user_delete_onlineuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='RegisterPet',
        ),
    ]
