# Generated by Django 4.2.1 on 2023-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_pet_registerpet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerpet',
            name='active',
        ),
        migrations.RemoveField(
            model_name='registerpet',
            name='begin_date',
        ),
        migrations.AddField(
            model_name='registerpet',
            name='age',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
