# Generated by Django 4.2 on 2023-04-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_task_completed_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='city',
        ),
    ]
