# Generated by Django 4.2 on 2023-05-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('resp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
    ]
