# Generated by Django 4.2 on 2023-05-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alergy_medicine_remove_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
