# Generated by Django 4.2.1 on 2023-05-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_event_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
