# Generated by Django 4.2 on 2023-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_medicine_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='time',
            field=models.DateTimeField(max_length=50),
        ),
    ]
