# Generated by Django 4.2.1 on 2023-05-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_medicine_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.pet')),
            ],
        ),
    ]
