# Generated by Django 4.2.1 on 2023-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_pet_photo_alergy_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(default='qualquer coisa', max_length=1),
        ),
    ]
