# Generated by Django 4.2.1 on 2023-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_event_colorselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(max_length=1),
        ),
    ]
