# Generated by Django 4.2.1 on 2023-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='background_color',
            field=models.CharField(choices=[('#978DCC', 'Purple'), ('#FAA42B', 'Orange'), ('#00B7D9', 'Blue'), ('#4FD881', 'Green')], default=0, max_length=8),
        ),
    ]
