# Generated by Django 4.2.1 on 2023-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_pet_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
