# Generated by Django 4.2.1 on 2023-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_medicine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(max_length=10),
        ),
    ]
