# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_alter_pet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergy',
            name='pet',
        ),
        migrations.AddField(
            model_name='alergy',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
