# Generated by Django 4.2.1 on 2023-05-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_taskanban_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanban',
            name='user',
        ),
    ]
