# Generated by Django 4.2.1 on 2023-05-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='time',
        ),
    ]
