# Generated by Django 4.2.1 on 2023-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_rename_date_todo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
