# Generated by Django 4.2.1 on 2023-05-31 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_todo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time',
            new_name='time_per_day',
        ),
    ]
