# Generated by Django 4.2.1 on 2023-05-31 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_rename_time_todo_time_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='medicine',
        ),
    ]
