# Generated by Django 4.2.2 on 2023-06-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_rename_title_todo_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med',
            field=models.CharField(default='exemplo', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='resp',
            field=models.CharField(default='exemplo', max_length=50),
        ),
    ]
