# Generated by Django 4.2.2 on 2023-06-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_medicine_med_alter_medicine_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='time',
            field=models.DateTimeField(default='101220232020', max_length=50),
        ),
    ]
