# Generated by Django 4.2.2 on 2023-06-08 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_alter_food_food_alter_food_resp_alter_food_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='colorSelected',
            field=models.CharField(default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
