# Generated by Django 4.2.2 on 2023-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_alter_event_colorselected_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='files/petracker_logo.png', null=True, upload_to='images/'),
        ),
    ]
