# Generated by Django 4.2.2 on 2023-06-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='https://raw.githubusercontent.com/bela975/PETracker/33735714a052b92ac15696326f3b398ce1924b49/img/petracker_logo.png', null=True, upload_to='images/'),
        ),
    ]
