# Generated by Django 4.2.2 on 2023-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='C:/Users/davim/Documents/fds-completo/PETracker/files/petracker_logo.png', null=True, upload_to='images/'),
        ),
    ]
