# Generated by Django 4.2.2 on 2023-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='PETracker\\static\\images\\images\\petracker_logo.png', null=True, upload_to=''),
        ),
    ]
